"""extra task priority, financial daily tasks, income and goals

Revision ID: b66ee63da1f4
Revises: d4361c4883e7
Create Date: 2026-07-22 18:06:46.096570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b66ee63da1f4'
down_revision: Union[str, Sequence[str], None] = 'd4361c4883e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_goals_user_id'), 'financial_goals', ['user_id'], unique=False)
    op.create_table('income_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('daily_task_instance_id', sa.UUID(), nullable=True),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('daily_task', 'manual')", name='ck_income_entry_source'),
    sa.ForeignKeyConstraint(['daily_task_instance_id'], ['daily_task_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['goal_id'], ['financial_goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_entries_daily_task_instance_id'), 'income_entries', ['daily_task_instance_id'], unique=False)
    op.create_index(op.f('ix_income_entries_entry_date'), 'income_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_income_entries_goal_id'), 'income_entries', ['goal_id'], unique=False)
    op.create_index(op.f('ix_income_entries_user_id'), 'income_entries', ['user_id'], unique=False)
    op.add_column(
        'daily_task_templates',
        sa.Column('is_financial', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('daily_task_templates', 'is_financial', server_default=None)
    op.add_column(
        'extra_tasks',
        sa.Column('priority', sa.Integer(), nullable=False, server_default='1'),
    )
    op.alter_column('extra_tasks', 'priority', server_default=None)
    op.create_check_constraint(
        'ck_extra_task_priority', 'extra_tasks', 'priority BETWEEN 1 AND 3'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_extra_task_priority', 'extra_tasks', type_='check')
    op.drop_column('extra_tasks', 'priority')
    op.drop_column('daily_task_templates', 'is_financial')
    op.drop_index(op.f('ix_income_entries_user_id'), table_name='income_entries')
    op.drop_index(op.f('ix_income_entries_goal_id'), table_name='income_entries')
    op.drop_index(op.f('ix_income_entries_entry_date'), table_name='income_entries')
    op.drop_index(op.f('ix_income_entries_daily_task_instance_id'), table_name='income_entries')
    op.drop_table('income_entries')
    op.drop_index(op.f('ix_financial_goals_user_id'), table_name='financial_goals')
    op.drop_table('financial_goals')
    # ### end Alembic commands ###
